services:
  app:
    build: .
    container_name: uptime_app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://monitor:monitor@db:5432/uptime
    volumes:
      - ./sites.json:/app/sites.json

  db:
    image: postgres:14
    container_name: uptime_db
    restart: always
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitor
      POSTGRES_DB: uptime
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor -d uptime"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
